export const REAC_CREATED = 'RECT_CREATED';

export const REAC_DELETED = 'REAC_DELETED';

export const DRAGGING = 'DRAGGING';

export const ADSORBED = 'ADSORBED';

export const CHOOSE_COMPONENT = 'CHOOSE_COMPONENT';

export const COMP_INSTACE_ACTIVE = 'COMPONENT_INSTACE_ACTIVE';
